-- Q1. What is the total revenue generated by male vs. female customers

Select gender, Sum(purchase_amount) as Total_Revenue
From customer
Group by gender ;

-- Q2. Which customers used a discount but still spent more than the average purchase amount

 Select customer_id, purchase_amount
 From customer
 Where discount_applied = 'Yes'
 And purchase_amount > (Select Avg(purchase_amount) From customer) ;
 
-- Q3. Which are the top 5 products with the highest average review rating

With  avg_rating as (
Select item_purchased, Round(Avg(review_rating), 2) as Avg_review_rating
From customer
Group by item_purchased  ),

ranked_avg_rating as (
Select *,
Dense_rank() Over(order by avg_review_rating Desc) as drnk
from avg_rating )

Select *
from ranked_avg_rating
where drnk <= 5 ;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

Select shipping_type, Avg(purchase_amount) as Avg_Purchase_Amnt
From customer
Where shipping_type in ('Standard', 'Express')
Group by shipping_type ;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

Select subscription_status,
Count(distinct customer_id) as Total_customers,
Round(Avg(purchase_amount), 2) as Avg_Spend,
Sum(purchase_amount) as Total_Revenue
From customer
Group by subscription_status ;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied

With discount_rates as (
Select item_purchased,
Round((Sum(Case When discount_applied = 'Yes' Then 1 End) / Count(*) ) * 100, 2) as discount_rate
From customer 
group by item_purchased ),

top_five_products as (
Select *,
Dense_Rank() Over(Order by discount_rate Desc) as drnk
From discount_rates )

Select item_purchased, discount_rate
From top_five_products 
Where drnk <= 5 ;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.

Select Case When previous_purchases = 1 Then 'New'
When previous_purchases >= 2 and previous_purchases <= 10 Then 'Returning'
When previous_purchases > 10 Then 'Loyal'
Else 'Invalid Num'
End as Customer_segment, Count(*) as Customer_Cnt
From customer
Group by customer_segment ;

-- Q8. What are the top 3 most purchased products within each category

With category_wise_cnt as (
Select Category, item_purchased, 
Count(item_purchased) as Cnt_item_purchased
From customer 
Group by category, item_purchased),

top_3_products as (
Select *,
Dense_Rank() Over(Partition by category Order by cnt_item_purchased Desc) as drnk
From category_wise_cnt )

Select *
From top_3_products
Where drnk <= 3 ;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe

Select subscription_status,
Count(customer_id) as repeat_buyers
From customer 
Where previous_purchases > 5
Group by subscription_status ;

-- Q10. What is the revenue contribution of each age group

Select age_group, Sum(purchase_amount) as Revenue
From customer 
Group by age_group 
Order by Revenue Desc ;